// File autogenerated by `./autogen.sh`, do not edit
#ifndef MEASUREMENT_KIT_SCRIPTING_HPP
#define MEASUREMENT_KIT_SCRIPTING_HPP
#include <measurement_kit/scripting/chai.hpp>
#include <measurement_kit/scripting/engine.hpp>
#include <measurement_kit/scripting/error.hpp>
#endif
